#!/bin/bash

echo "initialising replication on cluster-demo"

pushd cluster-demo
echo "STOP SLAVE;
CHANGE MASTER TO MASTER_HOST='mysql2', MASTER_PORT=3306, MASTER_USER='root', MASTER_PASSWORD='test', MASTER_AUTO_POSITION=1 FOR CHANNEL '2';
START SLAVE FOR CHANNEL '2';

CHANGE MASTER TO MASTER_HOST='mysql3', MASTER_PORT=3306, MASTER_USER='root', MASTER_PASSWORD='test', MASTER_AUTO_POSITION=1 FOR CHANNEL '3';
START SLAVE FOR CHANNEL '3';
" | docker-compose exec -T mysql1 mysql -u root -ptest

echo "STOP SLAVE;
CHANGE MASTER TO MASTER_HOST='mysql1', MASTER_PORT=3306, MASTER_USER='root', MASTER_PASSWORD='test', MASTER_AUTO_POSITION=1 FOR CHANNEL '1';
START SLAVE FOR CHANNEL '1';

CHANGE MASTER TO MASTER_HOST='mysql3', MASTER_PORT=3306, MASTER_USER='root', MASTER_PASSWORD='test', MASTER_AUTO_POSITION=1 FOR CHANNEL '3';
START SLAVE FOR CHANNEL '3';
" | docker-compose exec -T mysql2 mysql -u root -ptest

echo "STOP SLAVE;
CHANGE MASTER TO MASTER_HOST='mysql1', MASTER_PORT=3306, MASTER_USER='root', MASTER_PASSWORD='test', MASTER_AUTO_POSITION=1 FOR CHANNEL '1';
START SLAVE FOR CHANNEL '1';

CHANGE MASTER TO MASTER_HOST='mysql2', MASTER_PORT=3306, MASTER_USER='root', MASTER_PASSWORD='test', MASTER_AUTO_POSITION=1 FOR CHANNEL '2';
START SLAVE FOR CHANNEL '2';
" | docker-compose exec -T mysql3 mysql -u root -ptest
popd

